[profile.default]
# The source directory
src = 'contracts'

# The artifact directory
out = 'foundry/out'

# A list of paths to look for libraries in
libs = ['node_modules', 'foundry/lib']

# The test directory
test = 'test'

# Whether to cache builds or not
cache = true

# The cache directory if enabled
cache_path  = 'foundry/cache'

# Only run tests in contracts matching the specified glob pattern
match_path = '**/test/**/*.t.sol'

# The number of runs that must execute for each invariant test group. See also fuzz.runs
invariant = { runs = 16, depth = 16 }

# Fails the invariant fuzzing if a revert occurs
# fail_on_revert = true

[fmt]
# Style of uint/int256 types
int_types = 'long'

# Speed up compilation and tests during development
[profile.max]
fuzz = { runs = 256 }
invariant = { runs = 256, depth = 256 }

[profile.ci]
fuzz = { runs = 256 }
invariant = { runs = 256, depth = 16 }
