[profile.default]
# The source directory
src = 'contracts'

# The artifact directory
out = 'foundry/out'

# A list of paths to look for libraries in
libs = ['node_modules', 'foundry/lib']

# The test directory
test = 'test'

# Whether to cache builds or not
cache = true

# The cache directory if enabled
cache_path  = 'foundry/cache'

# Only run tests in contracts matching the specified glob pattern
match_path = '**/test/**/*.t.sol'

# Speed up tests during development by low values for fuzzing and invariant
fuzz = { runs = 256 }
invariant = { runs = 256, depth = 16 }

# Fails the invariant fuzzing if a revert occurs
# fail_on_revert = true

# Style of uint/int256 types
fmt = { int_types = 'long' }

### Profiles ###

# Profile for continuous integration
[profile.ci]
fuzz = { runs = 256 }
invariant = { runs = 256, depth = 16 }

# Profile for maximum testing, should be used for PR to master
[profile.max]
fuzz = { runs = 256 }
invariant = { runs = 256, depth = 256 }
