name: Checks

on: [push]

jobs:
  lint:
    name: Solidity and TypeScript linters
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      # here and below steps taken from official guide
      # https://pnpm.io/continuous-integration#github-actions
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup node.js version
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run Solidity linters
        run: pnpm lint:sol

      - name: Run TS linters
        run: pnpm lint:ts

  types:
    name: TypeScript types check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup node.js version
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Generate typechain types
        run: pnpm hardhat compile

      - name: Run TypeScript types check
        run: pnpm type:check

  test:
    name: Solidity tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup node.js version
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run Hardhat Solidity tests
        run: pnpm test

  coverage:
    name: Solidity coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup node.js version
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run Solidity coverage
        run: pnpm test:coverage
