name: Coverage

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  coverage:
    name: Hardhat Unit Tests Coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Common Setup
        uses: ./.github/workflows/setup

      # Remove the integration tests from the test suite, as they require a mainnet fork to run properly
      - name: Cleanup test from specs
        run: rm -rf test/integration/**/*.spec.ts

      - name: Run Solidity coverage
        run: yarn test:coverage

      - name: Produce the coverage report
        uses: insightsengineering/coverage-action@v2
        with:
          path: ./coverage/cobertura-coverage.xml
          publish: true
          diff: true
          diff-branch: master
          diff-storage: _core_coverage_reports
          coverage-summary-title: "Hardhat Unit Tests Coverage Summary"
          togglable-report: true
