name: Coverage

on:
  push:
    branches: [ master, develop, repovation ]
  pull_request:
    branches: [ master, develop, repovation ]

jobs:
  coverage:
    name: Solidity coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Run Solidity coverage
        run: yarn test:coverage

      - name: Produce the coverage report
        uses: insightsengineering/coverage-action@v2
        with:
          path: ./coverage/cobertura-coverage.xml
          publish: true
          diff: true
          diff-branch: master
          diff-storage: _core_coverage_reports
          coverage-summary-title: "Code Coverage Summary"
          togglable-report: true
