name: Linters

on: [push]

jobs:
  lint:
    name: Solidity and TypeScript linters
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Run Solidity linters
        run: yarn lint:sol

      - name: Run TS linters
        run: yarn lint:ts

  types:
    name: TypeScript types check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Generate typechain types
        run: yarn hardhat compile

      - name: Run TypeScript types check
        run: yarn typecheck
