name: Linters

on: [push]

jobs:
  solhint:
    name: Solhint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Common Setup
        uses: ./.github/workflows/setup

      - name: Run Solidity linters
        run: yarn lint:sol

  eslint:
    name: ESLint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Common Setup
        uses: ./.github/workflows/setup

      - name: Run TS linters
        run: yarn lint:ts

  typescript:
    name: TypeScript
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Common Setup
        uses: ./.github/workflows/setup

      - name: Generate typechain types
        run: yarn hardhat compile

      - name: Run TypeScript types check
        run: yarn typecheck
